config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :movies 
  resources :shows do
    resources :tickets
  end  

  root 'movies#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :showings, class_name: "Show"
  has_many :ticket_sales, through: :showings,  :source => :tickets

  validates :title, :rating, :length, presence: true

 
end

app/models/screen.rb
class Screen < ActiveRecord::Base
  has_many :shows
  has_many :movies, through: :shows

  validates :name, :seat_count, presence: true
  validates :name, uniqueness: true

end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :movie
  belongs_to :screen
  has_many :tickets

  validates :movie_id, :screen_id, :starting_time, presence: true
  validates :screen_id, uniqueness: { scope: :starting_time }

  
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessor :age 
  belongs_to :show

  validates :show_id, :first_name, :last_name, :email_address, presence: true
  validates :email_address, confirmation: true
  validates_format_of :email_address, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :credit_card_number, length: { minimum: 13 }
  validates :credit_card_number, length: { maximum: 19 }
  validate  :check_age
  validate  :check_card_is_valid?


  def create_age(ticket_params)
    @age = [ticket_params["age(1i)"], ticket_params["age(2i)"], ticket_params["age(3i)"]]
    @age = Date.new(@age[0].to_i, @age[1].to_i, @age[2].to_i)
  end

  def reset_cc_and_age(ticket)
    ticket.credit_card_number = 0
    ticket.age = nil
  end

  def check_card_is_valid?
    array_of_numbers = []
    total = 0
    credit_card_number.to_s.split(//).reverse.each_slice(2) do |x|
      array_of_numbers << (x.last.to_i*2)
      array_of_numbers << (x.first.to_i)
    end
    array_of_numbers.each do |num|
      if num.to_i > 9
        total += (num.to_i % 10)+1
      else 
        total += num.to_i
      end
    end
    n = credit_card_number.to_s.split('')
    unless total % 10 == 0 
      errors.add(:credit_card_number, "has an error, please check the numbers")
    end
  end

  def check_age
    if @age.present?
      age_to_validate = Date.new(@age[1], @age[2], @age[3])
      if age_to_validate <= Date.current - 18.years
        return true
      else
        errors.add(:age, "needs to be at least 18 years old to purchase the ticket.")
      end
    else
      false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all 
  end

end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  def new
    @ticket = Ticket.new
    @show = Show.find(params[:show_id])
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @show = Show.find(params[:show_id])
    @ticket.show_id = @show.id
    if ticket_params.has_key?(:age)
      @ticket.create_age(ticket_params)
    end
    if @ticket.save
      @ticket.show.increment!(:seats_sold)
      TicketMailer.ticket_receipt(@ticket).deliver_now
      flash[:notice] = "Your ticket to #{@show.movie.title} was purchased.  Please look for an email with your receipt. "
      redirect_to root_path
    else
      @errors = @ticket.errors.full_messages
      reset_cc_and_age(@ticket)
      render 'tickets/new', locals: { ticket: @ticket }
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:first_name, :last_name, :email_address, :email_address_confirmation, :credit_card_number, :credit_card_expiration_date, :age) 
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_errors.html.erb
<div class="alert-danger">
  <% if @errors%>
    <% @errors.each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <h1>Movie Theater</h1>
</div>

app/views/layouts/_notices.html.erb
<div class="alert-success" >
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Theater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>
  <%= render 'layouts/notices' %>
  <%= yield %>
</div>


</body>
</html>

app/views/movies/index.html.erb
<div id="movies">

  <% @movies.each do |movie| %>
    <div class="col-md-4 bottom-buffer">
      <h3><%= movie.title %></h3>
      <ul>
          <li><%= movie.rating %>  <%= movie.length %> minutes</li>
        <% movie.showings.each do |show| %>
            <%= show.starting_time.strftime("Starting at %I:%M%p") %>
            <% if show.seats_sold == show.screen.seat_count %>
              Sold Out
            <% else %>
              <%= link_to "Get a Ticket", new_show_ticket_path(show.id) %>
            <% end %>
        <% end %>
      </ul>
      </div> 
    <% end %>
</div>  


  

app/views/tickets/_form.html.erb
<ul id="well">
  <li>Movie: <%= @show.movie.title %></li>
  <li>Showtime: <%= @show.starting_time.strftime("%A, %B %d, %Y at %I:%Mpm") %></li>
</ul>
<%= form_for [:show, @ticket], :html => {:class=>"form-horizontal center", :role=>"form"} do |f| %>
  <div class="form-group">
    <%= f.label :first_name, class:"control-label col-sm-2" %>
    <%= f.text_field :first_name %><br />
  </div>
  <div class="form-group">
    <%= f.label :last_name, class:"control-label col-sm-2" %>
    <%= f.text_field :last_name %><br />
  </div>
  <div class="form-group">
    <%= f.label :email_address, class:"control-label col-sm-2" %>
    <%= f.text_field :email_address %><br />
  </div>
  <div class="form-group">
    <%= f.label :email_address_confirmation, class:"control-label col-sm-2" %>
    <%= f.text_field :email_address_confirmation %><br />
  </div>
  <div class="form-group">
    <%= f.label :credit_card_number, class:"control-label col-sm-2" %>
    <%= f.text_field :credit_card_number %><br />
  </div>
  <div class="form-group">
  <%= f.label :credit_card_expiration_date, 'Expiration date' , class:"control-label col-sm-2" %><br />
  <%= f.date_select :credit_card_expiration_date, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :use_month_numbers => true %><br />
  </div>
  <% if @show.movie.rating == "R" %>
    <div class="form-group">
      <%= f.label :age, "This movie is rated 'R'. Please provide your birthdate to purchase the ticket", class:"control-label col-sm-2" %><br />
      <%= f.date_select :age, :start_year => Time.now.year - 10, :end_year => (Time.now.year - 100) %><br />
    </div>
  <% end %>
  <%= f.submit "Buy the Movie Ticket" %>
<% end %>

app/views/tickets/new.html.erb
<%= render 'layouts/errors' %>
<div id="new_ticket">
  <%= render 'form' %>
</div> 